var child = [
  { 'dupe': false, 'type': 8, 'name': 'all.css', 'dir': 'c0', 'linked': 2, 'url': 'http://10.10.10.2/mysite/all.css', 'fetched': true, 'code': 200, 'len': 55183, 'decl_mime': 'text/css', 'sniff_mime': 'text/css', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xfff6d5cd },
  { 'dupe': false, 'type': 8, 'name': 'bootstrap.bundle.min.js', 'dir': 'c1', 'linked': 2, 'url': 'http://10.10.10.2/mysite/bootstrap.bundle.min.js', 'fetched': true, 'code': 200, 'len': 78635, 'decl_mime': 'application/javascript', 'sniff_mime': 'text/plain', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xfff6d5cd },
  { 'dupe': false, 'type': 8, 'name': 'bootstrap.min.cs', 'dir': 'c2', 'linked': 2, 'url': 'http://10.10.10.2/mysite/bootstrap.min.cs', 'fetched': true, 'code': 200, 'len': 67285, 'decl_mime': '[none]', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 2, 0, 0, 0, 0 ], 'sig': 0xef71a0a4 },
  { 'dupe': false, 'type': 8, 'name': 'bootstrap.min.css', 'dir': 'c3', 'linked': 2, 'url': 'http://10.10.10.2/mysite/bootstrap.min.css', 'fetched': true, 'code': 200, 'len': 155758, 'decl_mime': 'text/css', 'sniff_mime': 'text/plain', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xfff6d5cd },
  { 'dupe': false, 'type': 8, 'name': 'jquery.slim.min.js', 'dir': 'c4', 'linked': 5, 'url': 'http://10.10.10.2/mysite/jquery.slim.min.js', 'fetched': true, 'code': 200, 'len': 71037, 'decl_mime': 'application/javascript', 'sniff_mime': 'text/plain', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 2, 0, 0, 1, 0 ], 'sig': 0x43e46831 },
  { 'dupe': false, 'type': 8, 'name': 'register.css', 'dir': 'c5', 'linked': 2, 'url': 'http://10.10.10.2/mysite/register.css', 'fetched': true, 'code': 200, 'len': 2503, 'decl_mime': 'text/css', 'sniff_mime': 'text/plain', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xfff6d5cd },
  { 'dupe': false, 'type': 8, 'name': 'register.html', 'dir': 'c6', 'linked': 5, 'url': 'http://10.10.10.2/mysite/register.html', 'fetched': true, 'code': 200, 'len': 1987, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 2, 0, 0, 0, 0 ], 'sig': 0xfff5871c },
  { 'dupe': false, 'type': 64, 'name': 'C=N', 'dir': 'c7', 'linked': 2, 'url': 'http://10.10.10.2/mysite/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 2206, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x28f4fa31 },
  { 'dupe': false, 'type': 64, 'name': 'O=D', 'dir': 'c8', 'linked': 2, 'url': 'http://10.10.10.2/mysite/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 2206, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x28f4fa31 }
];
