var child = [
  { 'dupe': false, 'type': 8, 'name': 'a.gif', 'dir': 'c0', 'linked': 0, 'url': 'http://10.10.10.2/icons/a.gif', 'fetched': true, 'code': 200, 'len': 246, 'decl_mime': 'image/gif', 'sniff_mime': 'image/gif', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': false, 'type': 8, 'name': 'back.gif', 'dir': 'c1', 'linked': 2, 'url': 'http://10.10.10.2/icons/back.gif', 'fetched': true, 'code': 200, 'len': 216, 'decl_mime': 'image/gif', 'sniff_mime': 'image/gif', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': false, 'type': 8, 'name': 'blank.gif', 'dir': 'c2', 'linked': 2, 'url': 'http://10.10.10.2/icons/blank.gif', 'fetched': true, 'code': 200, 'len': 148, 'decl_mime': 'image/gif', 'sniff_mime': 'image/gif', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': true, 'type': 8, 'name': 'f.gif', 'dir': 'c3', 'linked': 0, 'url': 'http://10.10.10.2/icons/f.gif', 'fetched': true, 'code': 200, 'len': 236, 'decl_mime': 'image/gif', 'sniff_mime': 'image/gif', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': false, 'type': 8, 'name': 'image2.gif', 'dir': 'c4', 'linked': 2, 'url': 'http://10.10.10.2/icons/image2.gif', 'fetched': true, 'code': 200, 'len': 309, 'decl_mime': 'image/gif', 'sniff_mime': 'image/gif', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': true, 'type': 8, 'name': 'index.gif', 'dir': 'c5', 'linked': 0, 'url': 'http://10.10.10.2/icons/index.gif', 'fetched': true, 'code': 200, 'len': 268, 'decl_mime': 'image/gif', 'sniff_mime': 'image/gif', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': true, 'type': 8, 'name': 'left.gif', 'dir': 'c6', 'linked': 0, 'url': 'http://10.10.10.2/icons/left.gif', 'fetched': true, 'code': 200, 'len': 172, 'decl_mime': 'image/gif', 'sniff_mime': 'image/gif', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': true, 'type': 8, 'name': 'link.gif', 'dir': 'c7', 'linked': 0, 'url': 'http://10.10.10.2/icons/link.gif', 'fetched': true, 'code': 200, 'len': 249, 'decl_mime': 'image/gif', 'sniff_mime': 'image/gif', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': false, 'type': 8, 'name': 'p.gif', 'dir': 'c8', 'linked': 0, 'url': 'http://10.10.10.2/icons/p.gif', 'fetched': true, 'code': 200, 'len': 237, 'decl_mime': 'image/gif', 'sniff_mime': 'image/gif', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': true, 'type': 8, 'name': 'script.gif', 'dir': 'c9', 'linked': 0, 'url': 'http://10.10.10.2/icons/script.gif', 'fetched': true, 'code': 200, 'len': 242, 'decl_mime': 'image/gif', 'sniff_mime': 'image/gif', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': true, 'type': 8, 'name': 'text.gif', 'dir': 'c10', 'linked': 2, 'url': 'http://10.10.10.2/icons/text.gif', 'fetched': true, 'code': 200, 'len': 229, 'decl_mime': 'image/gif', 'sniff_mime': 'image/gif', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': true, 'type': 8, 'name': 'unknown.gif', 'dir': 'c11', 'linked': 2, 'url': 'http://10.10.10.2/icons/unknown.gif', 'fetched': true, 'code': 200, 'len': 245, 'decl_mime': 'image/gif', 'sniff_mime': 'image/gif', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff }
];
